"""update refresh sessions

Revision ID: 61323597f993
Revises: b0ea60c288c4
Create Date: 2026-07-14 18:12:36.289764

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '61323597f993'
down_revision: Union[str, Sequence[str], None] = 'b0ea60c288c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
