"""add user ownership

Revision ID: 84a99accdd9f
Revises: 1339ad8a65b6
Create Date: 2026-07-07 11:21:45.886259

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '84a99accdd9f'
down_revision: Union[str, Sequence[str], None] = '1339ad8a65b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_unique_constraint('unique_categories_for_user_id', 'categories', ['user_id', 'name'])
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('expenses', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('tags', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_unique_constraint('unique_tags_for_user_id', 'tags', ['user_id', 'name'])
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint('unique_tags_for_user_id', 'tags', type_='unique')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_column('tags', 'user_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_column('expenses', 'user_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint('unique_categories_for_user_id', 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_column('categories', 'user_id')
    # ### end Alembic commands ###
