"""add refresh sessions

Revision ID: b0ea60c288c4
Revises: 84a99accdd9f
Create Date: 2026-07-14 17:30:41.084901

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'b0ea60c288c4'
down_revision: Union[str, Sequence[str], None] = '84a99accdd9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
