"""updated nullable parameters

Revision ID: bcb793646daf
Revises: 9da95073c4ed
Create Date: 2026-06-23 15:42:09.307035

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'bcb793646daf'
down_revision: Union[str, Sequence[str], None] = '9da95073c4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
