"""updated ON DELETE options

Revision ID: be948f930c74
Revises: bcb793646daf
Create Date: 2026-06-23 15:58:44.984636

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'be948f930c74'
down_revision: Union[str, Sequence[str], None] = 'bcb793646daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('expense_tags_tag_id_fkey'), 'expense_tags', type_='foreignkey')
    op.drop_constraint(op.f('expense_tags_expense_id_fkey'), 'expense_tags', type_='foreignkey')
    op.create_foreign_key(None, 'expense_tags', 'expenses', ['expense_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'expense_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('expenses_category_id_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_category_id_fkey'), 'expenses', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'expense_tags', type_='foreignkey')
    op.drop_constraint(None, 'expense_tags', type_='foreignkey')
    op.create_foreign_key(op.f('expense_tags_expense_id_fkey'), 'expense_tags', 'expenses', ['expense_id'], ['id'])
    op.create_foreign_key(op.f('expense_tags_tag_id_fkey'), 'expense_tags', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###
